sudo: required
language: bash

# Required external env variables:
# - PROJECT: Google Cloud Platform project, e.g: my-project
# - BASE64_KEY: Base64 encoded service account json key for $PROJECT
# Optional external env variables:
# - REGISTRY: Google Cloud Registry, e.g.: gcr.io/my-project
# - BUCKET: Google Cloud Storage bucket, e.g.: my-bucket
env:
  global:
    - GCLOUD_CMD=google-cloud-sdk/gcloud/bin
    - KEYFILE=service-account.json
  matrix:
    - NAME=mysql5 TAG=5.5 DOCKERFILE_DIR=5.5
    - NAME=mysql5 TAG=5.6 DOCKERFILE_DIR=5.6
    - NAME=mysql5 TAG=5.7 DOCKERFILE_DIR=5.7
    - NAME=mysql8 TAG=8.0 DOCKERFILE_DIR=8.0

before_script:
  - if [ -z "$REGISTRY" ]; then export REGISTRY="gcr.io/$PROJECT"; fi
  - if [ -z "$BUCKET" ]; then export BUCKET="$PROJECT.appspot.com"; fi
  - env | sort

install:
  - scripts/extract-keyfile.sh
  - scripts/setup-gcloud.sh
  
script:
  - scripts/build.sh
